name: Deploy Python App to EC2
run-name: ${{ github.actor }} is zip the file and push to EC2 🚀
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "🐧 This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "🔎 The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v4
      - run: echo "💡 The ${{ github.repository }} repository has been cloned to the runner."
      - run: echo "🖥️ The workflow is now ready to test your code on the runner."
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.9"    
          
      - name: Package application
        run: |
          pip install -r requirements.txt --target ./libs
          tar -czf coin.tar.gz \
          --exclude=".git" \
          --exclude=".github" \
          --exclude=".venv" \
          --exclude="venv" \
          .

      - name: Copy tar.gz EC2
       uses: appleboy/scp-action@master
       with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USERNAME }}
        key: ${{ secrets.EC2_SSH_KEY }}
        source: "coin.tar.gz"
        target: "/home/${{ secrets.EC2_USERNAME }}/app

      - namee: Deploy on EC2
        uses: appleboy/ssh-action@master
        with:
         host: ${{ secrets.EC2_HOST }}
         username: ${{ secrets.EC2_USERNAME }}
         key: ${{ secrets.EC2_SSH_KEY }}
         script: |
          mkdir -p /home/${{ secrets.EC2_USERNAME }}/app/dist
          cd /home/${{ secrets.EC2_USERNAME }}/app
          tar -xzf coin.tar.gz -C ./dist
          rm coin.tar.gz
