name: Test EC2 Deploy

on:
  workflow_dispatch:

permissions: 
  id-token: write
  contents: read
  
jobs:
  test-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials using OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_RPLE_ARN }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Test AWS OIDC authentication
        run: |
          aws sts get-caller-identity

      - name: Get GitHub Runner public IP
        id: runner-ip
        run: |
          RUNNER_IP=${(curl -s https://checkip.amazonaws.com)
          echo "runner_ip=$RUNNER_IP" >> "$GITHUB_OUTPUT"
          echo "Runner IP : $RUNNER_IP"
          
      - name: Allow SSH from GitHub Runner
        run: |
          aws ec2 authorize-security-group-ingress \
          --group-id ${{ secrets.EC2_SECURITY_GROUP_ID }} \
          --protocol tcp \
          --port 22 \
          --cidr ${{ steps.runner-ip.outputs.runner_ip }}/32

      - name: Test SSH Connection
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script:  |
            echo "SSH connection successful"
            hostname
            whoami

      - name: Create test file
        run: |
          echo "GitHub Actions deployment test" > deploy-test.txt"

      - name: Test SCP
        uses: appleboy/scp-action@v1
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          source: "deploy-test.txt"
          target: "/home/${{ secrets.EC2_USERNAME }}/"

      - name: Remove SSH rule
        if: always()
        run: |
          aws ec2 revoke-security-group-ingress \
            --group-id ${{ secrets.EC2_SECURITY_GROUP_ID }} \
            --protocol tcp \
            --port 22\
            --cidr ${{ steps.runner-ip.outputs.runner_ip }}/32
            
